### ISSUE TITLE
which sequences did you use in KITTY dataset?

### ISSUE THREAD

**Issue by aiyaqing** [ZhiChen902/SC2-PCR#3]
hello,i try to run you code but i found the TE is 79.43, i use you fpfh data.
I want to use initial kitty dataset, what can i do?

**Comment by ZhiChen902** [comment]
I retest the result, and it is normal. How do you test the results? Colud show me the results you test?

**Comment by ZhiChen902** [comment]
I retest the result, and it is normal. How do you test the results? Could show me the results you test?

**Comment by ZhiChen902** [comment]
When you test on the KITTI dataset using fpfh descriptor, you should change the "data_path" in the json file to the path of fpfh dataset, and change the "descriptor" as fpfh. I don't know if you have a wrong configuration here.
![image](https://user-images.githubusercontent.com/54473539/170704561-33d62a23-0ce5-42c3-9c26-d22d9e1f1b9c.png)

**Comment by aiyaqing** [comment]
I am sorry that I did not reply because I was busy. Yes, I adjusted the parameters, and the TE of the code I ran was between 60 and 80. Now I'm writing a visual display of the point cloud after registration.
![062afdcf965ca96a6e4ed65c41daf1e](https://user-images.githubusercontent.com/56470789/170983969-ddf834ea-6c1c-432c-b56c-a6e62cdd7dc5.jpg)
![image](https://user-images.githubusercontent.com/56470789/170984136-3ed29093-78ee-4bee-a945-6b4153dc9e44.png)

**Comment by ZhiChen902** [comment]
The printed information is the error of the mis-estimated matching pairs, not the whole error. It means only 64-th and 377-th point cloud pairs are wrongly estimated. The error of the whole dataset is printed at the end of the code. Since you use the cpu-version, which has no attribute 'max_memory_allocate', the following program is not running. You can comment the 'max_memory_allocate' and run it again.
